# veomni actor config, inheriting from trainer/config/actor/actor.yaml
defaults:
  # veomni optimizer config
  - ../optim@optim: veomni

  # veomni engine config
  - ../engine@veomni: veomni

  - actor

  # load the reference default config, then apply the fields in the current yaml
  - _self_

_target_: verl.workers.config.VeOmniActorConfig

strategy: veomni
